### ISSUE TITLE
Cloning wrong repo?

### ISSUE THREAD

**Issue by ghost** [Prodigy-Hacking/Redirector#4]
In the readme it says to clone the Main repo with all the hacks but in that repository there is no redirect directory, So Did you mean to say Prodigy-Hacking/Redirector? or am I just confused?

**Comment by PatheticMustan** [comment]
Sorry, what are you trying to do?

**Comment by ghost** [comment]
Just checking the code to see how this is done. I have not actually tried this.

**Comment by PatheticMustan** [comment]
Ah, I see.

The installations were not updated after we moved Redirector to its own repo 😅 

Thanks for this issue!
